# Usamos una imagen oficial de Python version 3.9 (ligera)
FROM python:3.9-slim

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# El contenedor se mantendrá encendido para que podamos entrar y ejecutar comandos
# Usamos tail -f /dev/null como un truco para que no se cierre inmediatamente
CMD ["tail", "-f", "/dev/null"]
